accounts/urls.py
from django.conf.urls import url

from views import LoginView, logout_view, register_view


urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^register/$', register_view, name='register'),
]

family_history/urls.py
from django.conf.urls import url

from views import DashboardView, ProgressFormView, ReportsView

urlpatterns = [
        url(r'^$', DashboardView.as_view(), name='dashboard'),
        url(r'^progress$', ProgressFormView.as_view(), name='progress'),
        url(r'^reports$', ReportsView.as_view(), name='reports'),
]

fh17/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

from fh17.views import HomeView
from fh17.views import ContactView
from fh17.views import ReportsView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^contact$', ContactView.as_view(), name='contact'),
    url(r'^reports$', ReportsView.as_view(), name='reports'),
    url(r'^fh/', include('family_history.urls', namespace='fh')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
]

profiles/urls.py
from django.conf.urls import url

from views import ProfileUpdateView

urlpatterns = [
    url(r'^update/(?P<pk>[0-9]+)/$', ProfileUpdateView.as_view(), name='update'),
]

fh17/views.py
from __future__ import unicode_literals

from django.db.models import Sum

from django.views.generic.base import TemplateView

from family_history.models import FamilyHistoryStats

class HomeView(TemplateView):
    template_name = 'fh17/home.html'

class ContactView(TemplateView):
    template_name = 'fh17/contact.html'

class ReportsView(TemplateView):
    template_name = 'fh17/reports.html'

    def get_context_data(self, *args, **kwargs):
        context = super(ReportsView, self).get_context_data(*args, **kwargs)

        eq = FamilyHistoryStats.objects.filter(profile__group='EQ')
        if eq:
            context['eq_generations_total'] = 0 + int(eq.aggregate(Sum('generations'))['generations__sum'])
            context['eq_names_total'] = 0 + int(eq.aggregate(Sum('names'))['names__sum'])
            context['eq_indexed_total'] = 0 + int(eq.aggregate(Sum('indexed'))['indexed__sum'])
            context['eq_memories_total'] = 0 + int(eq.aggregate(Sum('memories'))['memories__sum'])
        else:
            context['eq_generations_total'] = 0
            context['eq_names_total'] = 0
            context['eq_indexed_total'] = 0
            context['eq_memories_total'] = 0

        rs = FamilyHistoryStats.objects.filter(profile__group='RS')
        if rs:
            context['rs_generations_total'] = 0 + int(rs.aggregate(Sum('generations'))['generations__sum'])
            context['rs_names_total'] = 0 + int(rs.aggregate(Sum('names'))['names__sum'])
            context['rs_indexed_total'] = 0 + int(rs.aggregate(Sum('indexed'))['indexed__sum'])
            context['rs_memories_total'] = 0 + int(rs.aggregate(Sum('memories'))['memories__sum'])
        else:
            context['rs_generations_total'] = 0
            context['rs_names_total'] = 0
            context['rs_indexed_total'] = 0
            context['rs_memories_total'] = 0

        return context

fh17/templates/fh17/base.html
<!DOCTYPE html>
<html>
<head>
	{% load staticfiles %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <title>Friends of Craig Park YSA</title>

	<!--Site Icon-->
	<link rel="icon" href="{% static 'emerald/images/emerald_icon.png' %}">

    <!-- Bootstrap  -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!--Custom CSS-->
	<link rel="stylesheet" type="text/css" href="{% static 'fh17/css/test.css' %}" />
</head>

<body>
	{% for message in messages %}
		<div class="alert alert-{{ message.tags }}">{{ message }}</div>
	{% endfor %}
	<div id="auth">
		{% if request.user.is_authenticated %}

		<div>Welcome, <a id="username" href="{% url 'profiles:update' pk=request.user.profile.id %}">{% if user.first_name %}{{ user.first_name }}{% else %}{{ user.username }}{% endif %}</a></div>

		<div id="logout">
			<a id="logout" href="{% url 'accounts:logout' %}">Logout</a>
		</div>

		{% else %}
		<div>
			<a id="login" href="{% url 'accounts:login' %}">Login</a>
		</div>

		{% endif %}
	</div>
	<div class="container">
		<div id="page">
			<div class="topNaviagationLink"><a href="{% url 'home' %}">Home</a></div>
			<div class="topNaviagationLink"><a href="{% url 'fh:dashboard' %}">Family History Initiative</a></div>
			<!-- More links at the top can be added later
			<div class="topNaviagationLink"><a href="index.html">Events</a></div>
			<div class="topNaviagationLink"><a href="index.html">Housing</a></div>-->
			<div class="topNaviagationLink"><a href="{% url 'contact' %}">Contact</a></div>
			{% if request.user.is_superuser %}
			<div class="topNaviagationLink"><a href="{% url 'reports' %}">Reports</a></div>
			{% endif %}
		</div>
		<div id="mainPicture">
			<div class="picture">
				<img src="{% static 'fh17/images/newport_beach_temple.jpg' %}"/>
			</div>
		</div>
		<div class="contentBox">
			<div class="innerBox">
				{% block content %}
				{% endblock %}
			</div>
		</div>
	</div>

<!-- jquery -->
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>

<!-- Latest compiled and minified JavaScript -->
<script 
  src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" 
  integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" 
  crossorigin="anonymous"></script>
</body>
</html>

fh17/templates/fh17/contact.html
{% extends 'fh17/base.html' %}

{% block content %}
<div class="contentText">
	<h3>Bishop</h3>
	<p>Bishop Scott Stanford: (714)879-0474</p>
	<h3>Competition Coordinator</h3>
	<p>Jessica Allen: (714)486-9595</p>
	<h3>Website</h3>
	<p>Zac Yauney: (714)785-2336</p>
 </div>

 {% endblock %}

fh17/templates/fh17/form-snippet.html
{% csrf_token %}
{% for field in form %}
<div class="form-group">
	{{ field.label_tag }}
	{{ field }}
	<small data-html="true" class="form-text text-muted">{{ field.help_text }}</small>
</div>
{% endfor %}
<button type="submit" class="btn btn-primary" value="Submit" name="">Submit</button>

fh17/templates/fh17/home.html
{% extends 'fh17/base.html' %}

{% block content%}

<h1>Friends of Craig Park YSA</h1>
<div class="contentText">
	<br/>
</div>
<h1>Family History Initiative</h1>
<div class="contentText">
	<p> As a ward we are working to increase our participation 
		in Family History through Ward Goals and Competition this summer.
		Please see Family History Initiative Tab for More information
	</p>
	<br />
 </div>

 {% endblock %}

fh17/templates/fh17/reports.html
{% extends 'fh17/base.html' %}

{% block content %}

<table class="table">
	<tr>
		<th></th>
		<th>
			Elder's Quorum
		</th>
		<th>
			Relief Society
		</th>
	</tr>
		<td>
			Generations
		</td>
		<td>
			{{ eq_generations_total }}
		</td>
		<td>
			{{ rs_generations_total }}
		</td>
	<tr>
	</tr>
		<td>
			Names
		</td>
		<td>
			{{ eq_names_total }}
		</td>
		<td>
			{{ rs_names_total }}
		</td>
	<tr>
	</tr>
		<td>
			Indexed
		</td>
		<td>
			{{ eq_indexed_total }}
		</td>
		<td>
			{{ rs_indexed_total }}
		</td>
	<tr>
	</tr>
		<td>
			Memories
		</td>
		<td>
			{{ eq_memories_total }}
		</td>
		<td>
			{{ rs_memories_total }}
		</td>
	<tr>

 {% endblock %}